# Welcome to Jekyll!

email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
title: Dunlin Management Ltd

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: kramdown
repository: dunlin-management/dunlin-management.com
plugins:
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: sunrise

collections:
  bms:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "single"
      toc: true
      toc_sticky: true

search: true
search_full_content: true
search_provider: lunr
future: true

